### PR TITLE
Project-specific file exclusions

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/phings#25

---

**Note:** Includes commits from https://github.com/websharks/phings/pull/24

### CODE REVIEW

**Comment by raamdev** [comment]
Referencing https://github.com/websharks/zencache-pro/pull/201

**Comment by jaswrks** [comment]
@raamdev Reviewed. Nice!

Would you mind naming the exclusion variables to something that is just a bit more context-specific please? e.g., `other_zip_tgz_fileset_exclusions`. I see that being easier to deal with should anything change in the future, and it will give us more granular control over other areas moving forward.

**Comment by raamdev** [comment]
> Would you mind naming the exclusion variables to something that is just a bit more context-specific please? e.g., other_zip_tgz_fileset_exclusions.

Done. Keep in mind the reason I originally went with `project_exclusions` was to keep the format of all the other properties in the the `.build.props` file (see the updated example file in https://github.com/websharks/phings/commit/f62aac349e30ebd729bf83509656f07c1f9918ca).

**Comment by jaswrks** [comment]
Thanks! :-)

> Keep in mind the reason I originally went with project_exclusions

Copy that. Please add the `project_` prefix to those also then, I agree.

e.g., `project_other_zip_tgz_fileset_exclusions`

If you can add those to the `example.props` file also that'd be great, then I'll review again.
https://github.com/websharks/phings/blob/000000-dev/src/psr4/example.props

**Comment by raamdev** [comment]
> If you can add those to the example.props file also that'd be great

I did... https://github.com/websharks/phings/blob/f62aac349e30ebd729bf83509656f07c1f9918ca/src/psr4/example.props :-) But let me update it with the `project_` prefix... one sec.

**Comment by jaswrks** [comment]
> I did... https://github.com/websharks/phings/blob/f62aac349e30ebd729bf83509656f07c1f9918ca/src/psr4/example.props :-)

Ah, sorry. I missed that. TY :-)

**Comment by raamdev** [comment]
@jaswsinc Done. https://github.com/websharks/phings/commit/4f6dc00812d90b991987cc5ab014f0516a205d44

**Comment by jaswrks** [comment]
@raamdev Great! Thanks.

I added a few minor tweaks to your work in https://github.com/websharks/phings/commit/04b2923e324f29a17b26de600d4dbba0bb74875b. If you can review and share any thoughts that you have I'd appreciate it. Otherwise, this looks ready to merge now.

**Comment by raamdev** [comment]
> I added a few minor tweaks to your work in 04b2923. If you can review and share any thoughts that you have I'd appreciate it. Otherwise, this looks ready to merge now.

Looks great to me! Thank you.

**Comment by raamdev** [comment]
@jaswsinc This is ready to merge. :-) I merged the dev branch into `feature/25` to confirm there were no conflicts.

**Pull request merged**
