### PR TITLE
During -lite target convert text domain references to string literals

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/phings#29

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc This is ready for a review. For testing, you can use the latest `feature/zencachecom74` branch from the `zencache-pro` repo (https://github.com/websharks/zencache-pro/pull/201), which includes an updated `.build.props` file that defines the new `project_lite_td_replace_regex_pattern` property.

**Comment by jaswrks** [comment]
Looks great so far! I ran a few tests and here are some things I noticed.
- `\$this->text_domain|SLUG_TD` should be:
  
  ```
  \$this\-\>text_domain|SLUG_TD
  ```
- Once I corrected that and ran another test, I found this in the old `includes/share.php` file.
  
  ```
  $this->slug = 'zencache' = str_replace('_', '-', __NAMESPACE__);
  ```
  
  We should probably exclude that file altogether somehow.
  
  Also, we need to be careful about replacing any instances of that word where it is used in a write context instead of being read as a function param.
  
  Something like this would make sure it only replaced where we intend it to be.
  
  ``` xml
  <regexp pattern="(,\s*)(${project_lite_td_replace_regex_pattern})(\))" replace="$1'${project_lite_slug}'$3" modifiers="u" />
  ```
  
  That will prevent this problem also.
  
  ``` php
  define(__NAMESPACE__.'\\'zencache'', 'zencache');
  ```
  
  Which should remain as-is; i.e.,...
  
  ``` php
  define(__NAMESPACE__.'\\SLUG_TD', 'zencache');
  ```

**Comment by raamdev** [comment]
@jaswsinc writes...

```
$this->slug = 'zencache' = str_replace('_', '-', __NAMESPACE__);
```

```
define(__NAMESPACE__.'\\'zencache'', 'zencache');
```

I did see both of those, but what is wrong with either one of those? I realize they look a little odd, but we're talking about something that happens as part of a generated build. It's not like that stuff gets committed...

> `\$this->text_domain|SLUG_TD` should be:
> 
> ```
> \$this\-\>text_domain|SLUG_TD
> ```

Copy that.

**Comment by jaswrks** [comment]
> $this->slug = 'zencache' = str_replace('_', '-', __NAMESPACE__);

In this case it creates a parse error. You can't assign a string literal a value.

> define(**NAMESPACE**.'\'zencache'', 'zencache');

This creates a parse error also, because of the extra/unexpected quotes.

**Comment by raamdev** [comment]
> creates a parse error

Hmm, odd. I wonder why that didn't show up when I tested the generated Lite version... or maybe I didn't test it. :grin: :sleeping: 

Thanks for catching that!

---

```
(,\s*)(${project_lite_td_replace_regex_pattern})(\))
```

Shouldn't that allow for whitespace between `SLUG_TD` and `)`?

```
(,\s*)(${project_lite_td_replace_regex_pattern})\s*(\))
```

**Comment by raamdev** [comment]
@jaswsinc See last commit. This PR is ready for another review.

**Comment by jaswrks** [comment]
> Shouldn't that allow for whitespace between SLUG_TD and )?

Awesome! Yes, it should. Great enhancement.

To preserve that whitespace, I suggest a minor tweak.

```
(,\s*)(${project_lite_td_replace_regex_pattern})(\s*\))
```

i.e., `(\s*\))`

**Comment by raamdev** [comment]
@jaswsinc writes...

> preserve that whitespace

Done.

**Pull request merged**
