### PR TITLE
PR: feature/36

### PR DESCRIPTION
**Pull request by jaswrks**
See: websharks/phings#36

### CODE REVIEW

**Comment by jaswrks** [comment]
Noting that the following command-line switch is now possible.

``` bash
phing build -D composer-lock-preserve=true
```

Or, running this target will force `composer-lock-preserve=true` automatically.

``` bash
phing post-receive-build
```

**Comment by jaswrks** [comment]
Noting that many property names defined in `.build.props` changed:
- `project_org` is now `project_owner`
- `project_ns` is now `project_namespace`
- `project_sns` is now `project_sub_namespace`
- `project_lite_ns` is now `project_lite_namespace`
- `project_lite_sns` is now `project_lite_sub_namespace`
- `project_php_up_to_version` is now `project_php_tested_up_to_version`
- `project_wp_up_to_version` is now `project_wp_tested_up_to_version`

**Comment by jaswrks** [comment]
@raamdev This is ready for another pair of eyes now.
Looks good to me and it tests well against the websharks/core.
~ Please see my notes above regarding property name changes.

**Comment by raamdev** [comment]
@jaswsinc Reviewed. Looks good to me. I tested the Phings `feature/39` branch against the dev branch of ZenCache Pro. It built the Pro and Lite version fine.

Please ping me against once these changes have been pushed to a new Phings release so that I can update the ZenCache `.build.props` file. :-)

**Comment by raamdev** [comment]
Noting that this PR probably closes https://github.com/websharks/phings/issues/33 too.

**Pull request merged**
