### PR TITLE
Allow including other files during Lite namespace replacement

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/phings#31

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc Ready for review.

**Comment by jaswrks** [comment]
Cool! Did you test this with an empty value also? I'm just curious to know what happens whenever there is an empty `<include pattern="" />` tag.

**Comment by raamdev** [comment]
> Did you test this with an empty value also?

Yes, works fine with an empty value.

**Comment by jaswrks** [comment]
In addition to this, would you mind also adding support for the `.x-php` extension? That is a special file extension that I use for templates and it is already defined in our `.gitattributes` file as well. https://github.com/websharks/dotfiles/blob/000000-dev/.gitattributes#L56

`.x-php` files are for placeholders like the `advanced-cache.txt` file, or example scripts; i.e., anything that is written in PHP, but that should be excluded from PHP evaluation at runtime.

So if we add support for the `.x-php` extension in all of those places where reflexive processing takes place in [this file](https://github.com/websharks/phings/blob/d56cac2ff83ca524eefaad7332014b6f0cf00956/src/psr4/targets/lite.xml#L172), then a project which happens to follow that standard would not need to make any additional customizations to its `.build.props`.

I think having both options is great though; i.e., `.x-php` or `project_lite_other_ns_replace_files_pattern`

_On minor advantage to using the `.x-php` extension, is that you can tell your IDE to interpret that extension as PHP, which makes navigating and/or viewing the file a bit easier when it comes to syntax highlighting._

---

As we add more and more of these project-specific adjustments, they are going to become harder and harder to remember and recognize over time—for me at least. For that reason, if we can be overly verbose in our naming of the build properties it might help. Thoughts?

```
project_lite_td_replace_regex_pattern = \$this\-\>text_domain|SLUG_TD
project_lite_other_ns_replace_files_pattern = src/includes/templates/advanced-cache.txt
```

Could become...

```
project_lite_text_domain_regex_replacement_pattern = \$this\-\>text_domain|SLUG_TD
project_lite_alter_namespace_in_other_files_pattern = src/includes/templates/advanced-cache.txt
```

**Comment by raamdev** [comment]
> For that reason, if we can be overly verbose in our naming of the build properties it might help. Thoughts?

That's fine with me, though if we're using the `ns` shorthand in other property names in that file (`project_ns`) I figured it made no sense to use the longer version elsewhere.

> would you mind also adding support for the .x-php extension?

Done. :-) See https://github.com/websharks/phings/commit/7b2310c1a7a4e5d6a4f342d0d1ac36695fa7d5ed.

**Comment by raamdev** [comment]
Another important thing to keep in mind: It's very important that we don't change these property names very often. Every change means that we need to go through all projects that currently use the Phing build script and make sure that their `.build.props` file has the correct property names. The more projects we have that are using the Phing build scripts, the more room there is for error.

**Comment by jaswrks** [comment]
> That's fine with me, though if we're using the ns shorthand in other property names in that file (project_ns) I figured it made no sense to use the longer version elsewhere.

Yep, good point. I wish I had named those differently from the start. I was trying to keep the names a bit shorter, but in practice it seems like the `.build.props` file is easier to deal with when it is verbose.

For instance, it's not clear (even to me), whenever I glance over the `.build.props` file what `project_sns` really is. I find myself looking back through the build script so I can try and remember what it was for.

> The more projects we have that are using the Phing build scripts, the more room there is for error.

Exactly, yes. At some point, if you agree, I'd like to rename the `ns` and `sns` properties to something more verbose. However, we will need to add back compat. for the shorter names too, if we do that.

**Comment by raamdev** [comment]
> we will need to add back compat. for the shorter names too, if we do that.

Why? 

> if you agree, I'd like to rename the ns and sns properties to something more verbose.

That's fine with me.

**Comment by jaswrks** [comment]
> Done. :-) See 7b2310c.

Thanks! :-)

Can you add support for `.x-php` here also:
https://github.com/websharks/phings/blob/7b2310c1a7a4e5d6a4f342d0d1ac36695fa7d5ed/src/psr4/targets/lite.xml#L173-L174

and here also:
https://github.com/websharks/phings/blob/7b2310c1a7a4e5d6a4f342d0d1ac36695fa7d5ed/src/psr4/targets/lite.xml#L206-L207

**Comment by jaswrks** [comment]
> we will need to add back compat. for the shorter names too, if we do that.
> Why?

Well, I guess we won't _need_ to, if we both update other projects accordingly. I was just assuming that we would want to avoid breaking any other files out there that might use those names.

**Comment by raamdev** [comment]
> I was just assuming that we would want to avoid breaking any other files out there that might use those names.

I don't think we have enough projects using the build scripts to justify building in backwards compatibility. I'd say it makes more sense to come up with a list of all projects using it, and then update them all at once.

**Comment by raamdev** [comment]
I forked this here so we can build a list of projects that use the build system and then update those: https://github.com/websharks/phings/issues/33

**Comment by jaswrks** [comment]
Cool :-)

**Comment by raamdev** [comment]
@jaswsinc In the meantime, can you merge this PR to `000000-dev` so that I can commit the changes here to the `.build.props` file for ZenCache (https://github.com/websharks/zencache-pro/pull/201)?

**Pull request merged**
