### PR TITLE
Exclude bourbon, .scss, and .map files from distribution ZIP/TGZ/PHAR

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/zencache#579

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc Review please. I'll let you merge this one when it's ready. Thanks!

**Comment by jaswrks** [comment]
Looks good to me! :100:

**Comment by raamdev** [comment]
@jaswsinc Did you see that I said I'd let you merge this when it's ready? :-) Wasn't sure if you missed that or if you were intentionally waiting to merge this.

**Comment by jaswrks** [comment]
Ah. I did see that, but for some reason it didn't occur to me that I should merge this. Ha! I'll do that now. Thanks for the heads up.

**Pull request merged**
