### PR TITLE
Add -push-lite-variation build target.

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/phings#1

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc Would appreciate some feedback here. I'm just getting us started building the `release` target and wanted to share my work so far so that we can collaborate a bit and so that you can give me some feedback. :-)

I still have to work out how we'll provide the multi-line commit message (with the changelog for that release), as the Phing [GitCommitTask](https://www.phing.info/docs/guide/trunk/GitCommitTask.html) only allows single-line commit messages. I had to use the ExecTask with `passthrough="true"` to run the `git commit` command, which allowed me to type a multi-line commit message in `vim`. However, I'm wondering if it would be better if we simply had a pre-built changelog file that we could attach to the commit using `git commit -F ./path/to/release/changelog.txt`. 

Still thinking this through...

**Comment by jaswrks** [comment]
Looks great so far. Nice work!

I don't see any problems, but I will leave a couple of inline notes in the latest diff just as observations.

> I had to use the ExecTask with passthrough="true" to run the git commit command, which allowed me to type a multi-line commit message in vim.

Ah. I see what you mean. Maybe it's easier just to use the `<exec>` task then. I found that to be the case on some things also; i.e., even though there are special tasks for certain things, running the `<exec>` task is a little more flexible.

**Comment by raamdev** [comment]
@jaswsinc I'm thinking if we make sure that `CHANGELOG.md` always contains the latest release changelog (right now it only contains an archive of older entries--the newest changelog entries only exist in `readme.txt`), we might be able to run some funky magic in the build script that searches that file for `= v%y%m%d =` with a version matching today's date, then grabs everything from that line down to the next `= v%y%m%d =` pattern and dump that into a temporary text file. We could then attach that temp file as the commit message when committing a release for the Lite version, so that the commit message contains the entire changelog for that release (with `= v%y%m%d =` as the first line of the commit message, which makes sense).

**Comment by jaswrks** [comment]
> funky magic in the build script that searches that file

Yep, that sounds awesome. I like funky magic also :ghost:

**Comment by jaswrks** [comment]
Feel free to merge this in at any time you like.

**Comment by raamdev** [comment]
@jaswsinc I added some funky magic. :man_with_gua_pi_mao: 

It's a _little_ hacky, but it works. I tried using RegexTask instead of ExecTask + `sed`, but I couldn't figure out how to get RegexTask to accept a property (the contents of `CHANGELOG.md` via LoadFileTask) as the `subject`.

**Comment by jaswrks** [comment]
@raamdev Funky magic looks good to me :-) :+1: 

> I tried using RegexTask instead of ExecTask + sed, but I couldn't figure out how to get RegexTask to accept a property (the contents of CHANGELOG.md via LoadFileTask) as the subject.

I see what you mean. Well, another way that you could go about this is to copy `CHANGELOG.md` to `.commit.msg` with the full changelog; i.e., instead of loading the changelog into the process, copy it into a new file. Then you can use a `<reflexive>` task with a `<filterchain>` and apply regex replacements on the file to strip away everything but the latest changelog entries.

There are some examples of this in the `-lite-variation` target.

Having said that. I don't see anything wrong with using `sed`. What you have looks fine. Perhaps you could tweak the regex a bit to look for `=\s`; i.,e., a space should appear after `^=` and before `=$`. That's an edge case though.

**Comment by jaswrks** [comment]
You might want to name `.commit.msg` with a leading `.~`; i.e., `.~commit.msg`. Just to make sure it is ignored by the `.gitignore` file; should it ever be left behind by mistake. Our `.gitignore` will automatically ignore any file/directory that starts with `.~`

**Comment by raamdev** [comment]
> You might want to name .commit.msg with a leading .~

Done. Thanks!

> Having said that. I don't see anything wrong with using sed

Yeah, I actually like the `sed` way of doing things. Seems a bit more straightforward to me.

> Perhaps you could tweak the regex a bit to look for =\s; i.,e., a space should appear after ^= and before =$.

Ah yes, I realized this last night after I went to bed. Thanks for pointing it out. I've updated the regex and tested it.

**Comment by jaswrks** [comment]
> Yeah, I actually like the sed way of doing things. Seems a bit more straightforward to me.

@raamdev I just wanted to share this with you regarding `sed`, because it might help you out whenever you move from PHP to JavaScript, then back to shell scripting again.

I like to stick with a single flavor of regex when I'm writing code, it helps me maintain some consistency with respect to regex when I move from one language to another. Since my primary focus is PHP/JavaScript, and because I use the `preg_*` functions in PHP; i.e., PCRE (perl-compatible regex), I try to stay away from `sed` altogether. The `sed` command does not support PCRE, but `perl` of course does. So instead of `sed -e 's//'` I use `perl -pe 's//'`

## Example

```
$ echo 'heLLo' | sed -e 's/^hello$/world/i'
# world
```

## Same As This...

```
$ echo 'heLLo' | perl -pe 's/^hello$/world/i'
# world
```

_Here you have all the power of PCRE, using the same regex flavor that we find in PHP/JavaScript._

**Comment by jaswrks** [comment]
Reference: http://stackoverflow.com/questions/6302025/perl-flags-pe-pi-p-w-d-i-t

**Comment by jaswrks** [comment]
Note: I am not suggesting that you change anything in the build script :-) I just wanted to share that with you in case it helps. I only learned this myself a few months ago.

**Comment by raamdev** [comment]
> Note: I am not suggesting that you change anything in the build script :-) I just wanted to share that with you in case it helps. I only learned this myself a few months ago.

Got it. Thanks for sharing that. :-)

I generally try to stay _away_ from Perl because of the myriad number versions that may be installed, and the differences between each. There's also differences between PCRE's specification and Perl's regular expression: http://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions#Differences_from_Perl

**Comment by jaswrks** [comment]
> I generally try to stay away from Perl because of the myriad number versions that may be installed

Are you referring to shell scripts and Perl specifically, or to PCRE in general?

**Comment by jaswrks** [comment]
For me, it is about the sed flavor in general; i.e., the BRE flavor which is now very old. I never learned this, I learn PCRE first, because I was working with PHP for the most part when I first started my career in programming. So the sed flavor is not as friendly to me.

The differences between PCRE and Perl are far less than the differences between BRE compared to JavaScript, PCRE, and Perl. JavaScript, PCRE, and Perl being very much the same, with just a few minor issues to be aware of between PCRE and Perl, and a few limitations that exist in JavaScript.

If you're already comfortable with BRE though, I can totally understand wanting to stick with this in shell scripts, and I do realize that it's far more compatible since it has been around for so long.

**Comment by raamdev** [comment]
> Are you referring to shell scripts and Perl specifically, or to PCRE in general?

I was referring to shell scripts and Perl. 

Your reasons for preferring PCRE makes total sense to me--I just have a habit of avoiding perl whenever a smaller tool (e.g., `sed`) will do the same job. :-)

**Pull request closed without merging**
