### PR TITLE
Many improvements. See: https://github.com/websharks/phings/issues/4

### PR DESCRIPTION
**Pull request by jaswrks**
## Changelog
- Making status output more verbose.
- Improving config and validation routines.
- Breaking targets into separate file imports.
- Making the entire repo more portable; i.e., it can be used as a submodule.
- Changing the name of the properties file. Now `.build.props` instead of `.build.properties`.
- Now suggesting the use of `build.xml` instead of `.build.xml`. This avoids the need to provide the path as a CLI arg; i.e., you can type `phing` instead of `phing -f .build.xml`.
- Changing hidden lite build target from `-lite-variation` to just `-lite`.
- Changing hidden lite push target from `-push-lite-variation` to just `-push-lite`.
- Refactoring temporary variables used in `-push-lite`. These now include a `_push_lite_` prefix to keep them unique.
- Breaking `-apigen` and the `codex` build target out of the normal build routine and into its own target.
- Now works in non-WordPress projects.
- Now works for projects with or without a `phar-stub.php`.
- Now works for projects with or without `wp-i18n-tools`.
- Now works for projects with or without `composer.json`.

### CODE REVIEW

**Comment by jaswrks** [comment]
@raamdev Please review when you have some time :-)

Referencing list of separate target files: https://github.com/websharks/phings/tree/feature/4/src/psr4/targets

**Comment by jaswrks** [comment]
## Once these changes are merged, the following will need to occur in projects that depend on these Phings:
- Rename existing `.build.properties` to `.build.props`
- Rename existing `.build.xml` to `build.xml`
- Update your `.gitattributes` file to [this](https://github.com/websharks/dotfiles/blob/000000-dev/.gitattributes).
- Modify the contents of your `build.xml` to the following (very small now).
  
  ``` xml
  <?xml version="1.0" encoding="UTF-8" ?>
  
    <project name="PHP PSR-4 Project" default="build">
      <import file="phings/src/psr4/targets.xml" />
    </project>
  ```
- Add a new submodule to bring the `websharks/phings` project in.
  
  ``` bash
  $ git submodule add git@github.com:websharks/phings.git phings
  ```

---

## Using the new Phing Build Script (Examples)

``` bash
$ phing # Formerly phing -f .build.xml
$ phing build # Same thing as the above.

$ phing codex # Separate. Can only be run after you run `$ phing build`.
$ phing release # Separate. Can only be run after you run `$ phing build`.
```

**Comment by raamdev** [comment]
> Once these changes are merged, the following will need to occur in projects that depend on these Phings:

When you say "once they are merged", do you mean _immediately_, as in the current `phing -f .build.xml` process used in several projects will suddenly stop working if these changes are merged right now? I don't think that's what you meant, but I want to be sure. :-)

**Comment by raamdev** [comment]
@jaswsinc Ping. ↑

**Comment by jaswrks** [comment]
> When you say "once they are merged", do you mean immediately

No. I mean if this is merged, once you update ZenCache to this version of the build script, those changes will need to be made in ZenCache in order for it to take advantage of this new layout.

**Comment by raamdev** [comment]
@jaswsinc Looks great to me! Feel free to merge this whenever you want, unless you want me to take care of that. :-)

**Pull request merged**
