### PR TITLE
feature/rewrite

### PR DESCRIPTION
**Pull request by jaswrks**
## Summary of Changes
- Reorganized targets into sub-directory classifications; e.g., all build targets are now in `targets/builds` and each set of builds are now nested into sub-directories indicating which phase they run in. For instance, `/in-base-dir`, `/in-base-dir-after`, `/in-build-dir`, `/in-build-dir-after`, etc.
- Several subtle enhancements and minor bug fixes throughout; e.g., improved exclusion patterns to reduce the time it takes to complete a build, additional Phing attributes throughout in order to improve consistency from one target to another, along with a better naming convention for targets and temporary target-specific variables which are now nested into sub-directories, and into separate Phing projects referenced via `<phingcall>` which puts each target into its own local scope as a way to avoid collisions.
- New build targets. Related (somewhat) to #80, though additional work may be needed to accomplish everything we want to at some point in the future.
- Updated (and new) build targets are as follows. **See:** [new wiki article](https://github.com/websharks/phings/wiki/Build-Targets) that lists all possible targets.
- Bug fix. Large files were sometimes being emptied out (YIKES, reported by @jaswsinc) and sometimes they were just stalling (YIKES, reported by @raamdev) and this seems to have been caused by i18n regex patterns that were in need of optimization. I was able to reproduce this against `classes/MenuPageOptions.php` in the Comet Cache software (a very large file) and the i18n text-domain regex patterns. Careful optimizations were made to these routines in order to resolve this issue. In addition, our Phing build script now runs `ini_set('pcre.backtrack_limit', (string) PHP_INT_MAX);` to help prevent random failures against very large files in the future.
- Bug fix. New ad hoc task deals w/ changelog extraction for lite pushing properly. See: #8. See also: `setups/adhocs/extract-changelog-for-version.xml`. Note that changelog extraction for a specific version requires that each of your version headers in the `CHANGELOG.md` file be in one of these formats: `= [version] =`, `= v[version] =`, `## [version]`, or `## v[version]`. Actually, `##` is not required if you use ATX-style headers. If you use ATX-style headers you may use any number of `#` markers; i.e., one `#` (or more) will do fine.
- Dotbuilds (i.e., `.build.php` files) are now processed in both the project base directory and also in the `.~build/${project_slug}` directory; i.e., if you name the file `.build.php` it runs in both directories (backward compatibility was preserved). **New:** To limit the scope of these files, you can change the name to either: `.build.in-base-dir.php` or `.build.in-build-dir.php` to get more specific about which phase you want your custom sub-routines to run in.
- The `-js-css` target (now named `-builds-in-build-dir-js-css-cleanup`) now runs in the `.~build/${project_slug}` directory phase, because it's only job is to tidy-up JS/CSS files before packaging compressed archives for distribution.
- Bug fix. ZIP and TGZ archives were incorrectly excluding `.ht*` files such as `.htaccess` in the packaging phase. While these files are not important when building a PHAR archive, they _are_ important to ship with a plugin (i.e., in `.tgz` and `.zip` files) for security purposes; e.g., to prevent direct access to files not intended for a web server.
- Improved the lite push target by accepting either `y` or `yes` as an answer to prompts, and it is no longer caSe-sensitive either.
- Improved the lite push target by adding `checkreturn="true"` to all `<exec>` tags; i.e., to be sure each command succeeds before continuing.
- Optimized the lite push target by excluding `/src/vendor` from the repo content that is pushed to the remote for the lite variation. The `/src/vendor` directory should not be included because that is handled by Composer via the `/composer.json` file in this repo; i.e., those are external dependencies that are not a part of the lite repo itself.
- Optimized the lite push target by adding the `depth="1"` attribute to the `<gitclone>` tag; i.e., only clone the last history phase, which reduces download time and bandwidth.
- Adding new exclusions to the archive generators: `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` are now excluded also. See also: `setups/patterns/*.xml`.
- Removed exclusions from archive generators: `AUTHORS.txt` and `CONTRIBUTORS.txt` are now unnecessary to exclude, as we already cover the `.md` version of these files; i.e., we don't have the `.txt` variations anyway, and that just adds additional fluff to an already long list of exclusions. Removing to clean things up just a bit. See also: `setups/patterns/*.xml`.
- New pattern sets in `setups/patterns/*.xml`: `_token_patternset`, `_wp_token_patternset`, `_dotbuilds_patternset`, `_text_based_patternset`, `_php_patternset`, `_js_css_patternset`, and `_lite_repo_patternset`. These are designed to keep things DRYer.
- In `targets/setups/patterns.xml`, all `<fileset>` tags were changed to `<patternset>` tags in order to make them slightly more versatile.
- Improving support for `.x-php` files throughout. These should be considered PHP files also, and therefore all PHP-related routines should search/replace/include those files when performing various operations. The `.x-php` extension is something that WebSharks uses for any type of PHP file that should not actually be processed by a web server; e.g., files that serve only as a template for the generation of something else; or files that serve only as example API calls, etc. Since these files may also contain namespace references or tokens that need to be replaced, they must be processed in the same way regular PHP files are—during the build phase.
  
  **Note:** We should try to update things like `advanced-cache.txt` to `advanced-cache.x-php` in the Comet Cache plugin, at which time the `.build.props` could be updated to remove `project_lite_alter_namespace_in_other_files_pattern`.
- Now skipping POT generation for the lite build variation. See: https://github.com/websharks/phings/issues/51#issuecomment-191911351.
- Now enforcing a text-domain that will always exclude any `-lite|pro` suffix; i.e., always use the base plugin slug as the i18n text-domain. See: https://github.com/websharks/phings/issues/51#issuecomment-191911351.
- All target-specific validators have been improved with respect to the `.~build/${project_slug}` directory being necessary; e.g., the linters, the codex, tests, and distro-related targets all require the project to have already been built first before they can be run. This is now enforced, and now instead of deleting the entire `.~build/` directory at the beginning of every `$ phing` call, the `.~build/` directory can be preserved, and only sub-directories it contains are overwritten as needed; i.e., to perform an action being requested. These improvements are also being implemented in an effort to help separate the lite|pro build routines (more on this below), so that it's possible to build one or the other instead of always both at the same time.
- Reducing the amount of output during a build (slightly) by removing overly verbose output like: "Deleting previous: ..." which was already followed by output from Phing itself.
- Moving all hidden `-setup-*` targets into `<project>` scope (via imports only) to reduce the number of times each individual setup target needs to be listed in various (visible) build targets. See: `targets.xml` and `imports.xml` for more information.
- Removing support for `$ phing ... -D composer-lock-preserve=true` in favor of that being the default, and now we have a new flag called `$ phing ... -D composer-lock-delete=true` to disable it. The default value can always be overridden by passing `$ phing ... -D composer-lock-delete=true|false`. Or, before running Phing you can simply delete the `composer.lock` file yourself if you want to delete it; i.e., not preserve dependency versions. See also: [It's All About the `.lock` File](https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file) for more information. Also, as a part of the reorganized codebase structure, the `-composer-lock-preserve` target was consolidated into a single target that reads the new flag.
- Bug fix. Adding `return` to regex `(namespace|use|return)` when replacing namespace references in various files. See #83.
- Bug fix. Exclude `.build.php` and `.build.*.php` files from TGZ and ZIP distro files. See also: `setups/patterns/lite-repo.xml`.
- Bug fix. Excluding `/assets` from lite push to remote repo. These assets should only be seen the pro repo. This also avoids PEAR compatibility issues with the Git LFS protocol. See also: `setups/patterns/lite-repo.xml`.
- Bug fix. Excluding `.gitmodules` from lite push to remote repo. There are no submodules in the final lite repo. This also avoids PEAR compatibility issues w/ recursive cloning. See also: `setups/patterns/lite-repo.xml`.
- Bug fix. Always look for a leading `\` slash when performing any type of namespace replacement.
- Completed a new round of tests against all build targets after the changes above.

### CODE REVIEW

**Comment by jaswrks** [comment]
@raamdev I am ready to merge a partial rewrite of the Phing build scripts. Please review the summary of changes above and let me know if you have any questions or change requests.

**Comment by jaswrks** [comment]
Don't miss this item in the changelog:
- Updated (and new) build targets are as follows. **See:** [new wiki article](https://github.com/websharks/phings/wiki/Build-Targets) that lists all possible targets.

---

So, with that information, a typical build (by a project lead) might look like this:
- `$ phing full-build-all` (to do a full build of everything).
- `$ phing release` (if you are ready to release; i.e., push the lite variation).

---
- `$ phing codex` (to generate a codex).

---

Kristine/Renz would run:
-  `$ phing build` (or just `$ phing`)
- And/or `$ phing build-lite`
- Or `$ phing build-all` (pro and lite shortcut)

**Comment by jaswrks** [comment]
@raamdev You should be able to test this branch in Comet Cache and find success. However, since you already have an RC out there for testing, I would advise against using this updated copy to do your next official release of the software, simply because so many changes occurred at once. I'm not aware of any back compat. breaks (other than changes to the build target names and intended functionality), but it would probably be easier to do your next official release with the existing `master` branch.

**Comment by raamdev** [comment]
@jaswsinc Wow, awesome! So many bug fixes and improvements that I can't wait to start using this.

> You should be able to test this branch in Comet Cache and find success. However, since you already have an RC out there for testing, I would advise against using this updated copy to do your next official release of the software, simply because so many changes occurred at once

Copy that. I agree. I'm planning to do a Comet Cache GA release tomorrow, so I'll be sure to do that with Phings v160411.

---

I just tried building the `000000-dev` branch of Comet Cache Pro using this `feature/rewrite` branch of Phing, but I got the following error. Will an update to each projects `build.xml` file be necessary? Are there any other changes that will need to be made to the projects when we switch them over to this rewritten version of the Phing scripts?

```
$ phing
Buildfile: /Users/raam/Projects/comet-cache-pro/build.xml
 [property] Loading /Users/raam/Projects/comet-cache-pro/.build.props
      [php] Evaluating PHP expression: preg_replace('/\-(?:lite|pro)$/ui', '', 'comet-cache-pro')
      [php] Evaluating PHP expression: str_replace('%y%m%d', date('ymd'), '%y%m%d')

BUILD FAILED
/Users/raam/Projects/comet-cache-pro/build.xml:4:15: /Users/raam/Projects/comet-cache-pro/phings/src/psr4/targets.xml:10:17: /Users/raam/Projects/comet-cache-pro/phings/src/psr4/imports.xml:18:12: phing.tasks.system.ImportTask doesn't support the 'fileset' creator/adder.
Total time: 0.2572 seconds
```

**Comment by jaswrks** [comment]
@raamdev writes...

> ImportTask doesn't support the 'fileset' creator/adder.

Hmm, sorry about that. I wonder if that's a new feature. What version of Phing are you running?

``` bash
$ phing -v
```

I have tested this branch with Phing v2.13.0 and v2.14.0 (latest) using PHP 7.0.5.

I just updated to v2.14.0 to try and reproduce this issue, but it's working as expected for me. As I was doing that I also updated the Homebrew Formula that I built a while back, so if you're using that Formula you should be able to upgrade like this:

``` bash
$ brew update
$ brew upgrade websharks-phing
```

If that doesn't work, uninstall all previous versions first, like this:

``` bash
$ brew update
$ brew uninstall websharks-phing --force
$ brew install websharks-phing
```

Or, you can download the PHAR file and install like this:

``` bash
$ curl http://www.phing.info/get/phing-2.14.0.phar --location --output /usr/local/bin/phing
```

**Comment by jaswrks** [comment]
> Will an update to each projects build.xml file be necessary?

No, the `build.xml` should remain the same, and it is expected to contain:

``` xml
<?xml version="1.0" encoding="UTF-8" ?>

<project name="PHP PSR-4 Project" default="build">
  <import file="phings/src/psr4/targets.xml" />
</project>
```

> Are there any other changes that will need to be made to the projects when we switch them over to this rewritten version of the Phing scripts?

No. I'm not aware of any BC breaks.

**Comment by jaswrks** [comment]
I noticed that this branch has some merge conflicts at the moment, so it might be a good idea to simply copy the files from this branch into Comet Cache (for now) while you're testing. I'll work out those conflicts whenever I merge this in though, so that won't be an issue moving forward.

``` bash
$ git clone websharks/comet-cache-pro ~/temp/comet-cache-pro --depth=1
$ git clone websharks/phings ~/temp/phings --branch=feature/rewrite --depth=1
```

``` bash
$ cd ~/temp/comet-cache-pro
$ cp -fr ~/temp/phings/. phings
```

``` bash
$ phing full-build-all
```

**Comment by raamdev** [comment]
> What version of Phing are you running?

Phing 2.10.1.

Upgrading to Phing v2.14.0 fixed that issue.

---

## Next problem...

Now the build fails at the PHPCS target with this:

```
FILE: .../.~build/comet-cache-pro/src/includes/traits/Ac/BrowserUtils.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 15 | ERROR | [x] Blank line found at start of control structure
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

However, running PHP CS Fixer on that file reports no changes necessary... 

```
/usr/local/bin/php-cs-fixer --config-file=/Users/raam/.php_cs --verbose fix /Users/raam/Projects/comet-cache-pro/src/includes/traits/Ac/BrowserUtils.php
Loaded config from "/Users/raam/.php_cs"
.
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 0.197 seconds, 5.000 MB memory used
```

**Comment by raamdev** [comment]
> I noticed that this branch has some merge conflicts at the moment, so it might be a good idea to simply copy the files from this branch into Comet Cache (for now) while you're testing.

For testing, I'm just changing into the `phings` directory of my Comet Cache Pro repo, then `git checkout feature/rewrite`. Then I go back into the root repo directory and run Phing. 

A merge conflict just means that the `feature/rewrite` branch cannot be fast-forward merged with the `000000-dev` branch _of the Phings repo_—that should have no effect on how I test it with Comet Cache Pro.

**Comment by jaswrks** [comment]
> A merge conflict just means that the feature/rewrite branch cannot be fast-forward merged with the 000000-dev branch of the Phings repo—that should have no effect on how I test it with Comet Cache Pro.

Copy that. Yes, I understand that and I agree. I probably shouldn't have mentioned _merge_ to put that suggestion into a merge context. What I was doing locally was copying files over to a temporary forked copy of the CC repo and changing the `.build.props` to make it possible to test against alternative remotes and run all of the targets for a complete set of tests. I was also hoping to avoid any bugs in this `feature/rewrite` branch causing unforeseen issues with the working clone of CC that I normally use.

**Comment by jaswrks** [comment]
@raamdev writes...

> Now the build fails at the PHPCS target with this:

Good, making progress there. With respect to this PHPCS issue, can you please try running it again after [my last commit](https://github.com/websharks/phings/pull/83/commits/aba5f7c636c1c80020b82c6b4463b87c4df082a8), which will turn on Sniff Codes in the output for us. What I'd like to see is two things:
- The version of PHPCS that you're running please.
- The specific Sniff Code that produces that error in the output for you.

---

I think the issue you're seeing might be coming from the latest release of PHPCS, which I have found to be buggy. Our current set of standards excludes the Sniff Code that I _think_ is being reported there, so what you're seeing shouldn't be considered an error when it runs. This, along with some other issues I noticed in previous tests with PHPCS 2.6 is why I moved back to v2.5.1 for now. Referencing: https://github.com/squizlabs/PHP_CodeSniffer/releases

Moving forward, I'm thinking it would be a good idea for us to just package PHPCS, PHPUnit, CasperJS, etc; together with the Phing project. That way we are all always on the same page when a build is being run locally or on the CI server.

**Comment by raamdev** [comment]
> I was also hoping to avoid any bugs in this feature/rewrite branch causing unforeseen issues with the working clone of CC that I normally use.

Well, since everything important in the Comet Cache repo is being controlled by Git, if the Phing scripts do anything unexpected you'll see those changes with a `git status` after running Phing and just run `git reset --hard`.

> I think the issue you're seeing might be coming from the latest release of PHPCS

I was running PHPCS v2.6.0 (stable). Switching back to v2.5.1 fixed the issue and now the build runs fine.

> Moving forward, I'm thinking it would be a good idea for us to just package PHPCS, PHPUnit, CasperJS, etc; together with the Phing project. That way we are all always on the same page when a build is being run locally or on the CI server.

Yes, that sounds like a great idea to me. We really need some way to make sure everybody is running the same version build tools when building, otherwise we're going to keep running into issues like this.

**Comment by jaswrks** [comment]
> I was running PHPCS v2.6.0 (stable). Switching back to v2.5.1 fixed the issue and now the build runs fine.

Cool. I'm going to work on bundling these dependencies.

> Well, since everything important in the Comet Cache repo is being controlled by Git, if the Phing scripts do anything unexpected you'll see those changes with a git status after running Phing and just run git reset --hard.

Great point. I was testing `$ phing release` also though, and that's how I was able to do a full commit and push to the remote repo when testing. I was working with a fork of the CC repo, copying the Phing system into that fork, modifying the `.build.props` `project_owner`, etc.

**Comment by raamdev** [comment]
> I was testing `$ phing release` also though

Ah, that makes sense. :-) A fork of the Comet Cache repo for that kind of testing would be good.

**Pull request merged**
